options=[
    "Roll Again",
    "Winner chooses any character",
    "Go 5 extra spaces",
    "One stock match",
    "Both Players start at 100%",
    "Timers on low",
    "Random stage with hazards",
    "Falcon ditto",
    "Items low",
    "Items medium",
    "Items high",
    "Mega smash",
    "Land a spike kill to auto win",
    "Final smash meter on",
    "Nobody can shield",
    "Baseball",
    "Opponent gets a level 2 cpu teammate",
    "Winner plays with Joy Con",
    "Both players taunt after every smash attack",
    "Winner SDs at the start of match"
];

extradetails=[
    "",
    "",
    "(8 total spaces)",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "(If you shield you take a medium attack)",
    "",
    "(Singular Joycon)",
    "",
    "",
    "",
];